export enum PermissionTypes {
  PERMISSION_ACTION_START = "PERMISSION_ACTION_START",
  PERMISSION_GET_SUCCESS = "PERMISSION_GET_SUCCESS",
  PERMISSION_GET_FAILED = "PERMISSION_GET_FAILED",
  PERMISSION_ACTION_END = "PERMISSION_ACTION_END",
}
